script: ./.travis/build
before_install:
- git submodule update --init --recursive
- sudo apt-get update -qq
- sudo apt-get install -qq doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev libblas-dev gfortran
compiler:
- clang
- gcc
notifications:
  email:
  - hpp-source@laas.fr
branches:
  only:
  - master
language: cpp
matrix:
  allow_failures:
  - compiler: clang
